import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Contacto() {
  return (
    <>
      <Head>
        <title>Retro Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/retrowiki.ico" />
      </Head>
      <div className="bg-gray-900">
        <div className="mx-auto max-w-3xl text-center">
          <h1 className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl mt-6">
            Retro Wiki
          </h1>
        </div>
        <article>
          <div className="mx-auto max-w-3xl">
            <div className="bg-white rounded-lg shadow-lg p-6">
              <h2 className="text-2xl font-bold text-gray-800">Contacto</h2>
              <p className="text-gray-600">
                Si tienes alguna duda o sugerencia, puedes contactarnos a través
                de nuestro correo electrónico.
              </p>
              <div className="mt-4">
                <label className="block text-gray-800">Nombre</label>
                <input
                  type="text"
                  className="w-full mt-2 rounded-lg border-gray-200 shadow-sm focus:border-green-500 focus:ring focus:ring-green-200 focus:ring-opacity-50"
                />
              </div>
              <div className="mt-4">
                <label className="block text-gray-800">
                  Correo electrónico
                </label>
                <input
                  type="email"
                  className="w-full mt-2 rounded-lg border-gray-200 shadow-sm focus:border-green-500 focus:ring focus:ring-green-200 focus:ring-opacity-50"
                />
              </div>
              <div className="mt-4">
                <label className="block text-gray-800">Mensaje</label>
                <textarea className="w-full mt-2 rounded-lg border-gray-200 shadow-sm focus:border-green-500 focus:ring focus:ring-green-200 focus:ring-opacity-50"></textarea>
              </div>
              <div className="mt-4">
                <button className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-lg">
                  Enviar
                </button>
              </div>
            </div>
          </div>
        </article>
      </div>
    </>
  );
}
