import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import LandingPage from "./landingPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Retro Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/retrowiki.ico" />
      </Head>
      <Link href="./landingPage"> haz click en mi xd</Link>
      <Link href="./loginPage"> Intenta iniciar Sesion</Link>
      <Link href="./contactoPage"> Contacto</Link>
    </>
  );
}
