//TODO: migration to change email to email_adress
//TODO: Agregar un baner o icono al login
//TODO: Add JWT
import NavBar from "@/layouts/header/navBar";
import Head from "next/head";
import React, { useState } from 'react'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

function LoginPage() {
  const [email,setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");

  const handleSubmit = (e : React.FormEvent<HTMLFormElement>) => {};

  return (
    <>
      <Head>
        <title>Retro Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/retrowiki.ico" />
      </Head>
      <NavBar/>
      <div className={inter.className}>
        <div className="flex items-center justify-center h-screen  bg-gray-900">
          <div>
            <section>
              <h2 className="mt-6 text-center text-3xl font-extrabold text-white">
                Inicia sesión
              </h2>
            </section>

            <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
              {/* Email Textbox */}
              <div className="rounded-md shadow-sm -space-y-px">
                <label htmlFor="email_adress" className="text-white mb-2"> Correo: </label>
                <input id="email_adress" name="email_adress" type="email" autoComplete="email" required placeholder="Ejemplo@correo.com"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-primary focus:border-primary focus:z-10 sm:text-sm"
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              {/* Password Textbox */}
              <div>
                  <label htmlFor="password" className="text-white mb-2">
                    Contraseña
                  </label>
                  <input
                    id="password"
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    required
                    className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-primary focus:border-primary focus:z-10 sm:text-sm"
                    placeholder="Contraseña"
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
              {/* Submit Button */}
              <div className="flex justify-center">
                <button className="rounded-full bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-blue-700">
                  Inicia Sesion
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

    </>
  )
}

export default LoginPage